# Generated by Django 5.0 on 2024-02-29 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0042_updatecashin_division_updatecashin_projects_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AvailableBalance',
        ),
        migrations.DeleteModel(
            name='Dashboard',
        ),
        migrations.DeleteModel(
            name='Summary',
        ),
        migrations.DeleteModel(
            name='UpdateCashIn',
        ),
        migrations.DeleteModel(
            name='UpdateCashOut',
        ),
    ]
