# Generated by Django 5.0 on 2024-03-13 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0043_delete_availablebalance_delete_dashboard_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_provided', models.TextField()),
                ('packing_options', models.TextField()),
                ('purchase_price_cif_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('does_price_change_per_package', models.BooleanField(default=False)),
                ('payment_terms', models.CharField(max_length=255)),
                ('lead_time_weeks', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='UserActionLog',
        ),
    ]
