# Generated by Django 5.0 on 2024-03-13 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0044_supplier_delete_useractionlog'),
    ]

    operations = [
    ]
