# Generated by Django 5.0 on 2024-03-13 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0046_useractionlog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserActionLog',
        ),
    ]
