# Generated by Django 5.0 on 2024-03-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0047_delete_useractionlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_date', models.DateField()),
                ('material', models.TextField()),
                ('packing', models.TextField()),
                ('supplier', models.CharField(max_length=255)),
                ('total_purchase_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=255)),
                ('payment_requirement_dates', models.DateField()),
                ('expected_eta', models.DateField()),
                ('expected_clearance_date', models.DateField()),
                ('updated_eta1', models.DateField(blank=True, null=True)),
                ('updated_eta2', models.DateField(blank=True, null=True)),
                ('actual_arrival', models.DateField(blank=True, null=True)),
                ('clearance_time_days', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
