# Generated by Django 5.0 on 2024-03-17 07:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopflee', '0048_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='material',
            new_name='material_supplied',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='payment_method',
            new_name='packing_options',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='total_purchase_price',
            new_name='selling_price_per_unit',
        ),
        migrations.RemoveField(
            model_name='project',
            name='actual_arrival',
        ),
        migrations.RemoveField(
            model_name='project',
            name='clearance_time_days',
        ),
        migrations.RemoveField(
            model_name='project',
            name='expected_clearance_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='expected_eta',
        ),
        migrations.RemoveField(
            model_name='project',
            name='packing',
        ),
        migrations.RemoveField(
            model_name='project',
            name='payment_requirement_dates',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_eta1',
        ),
        migrations.RemoveField(
            model_name='project',
            name='updated_eta2',
        ),
        migrations.AddField(
            model_name='project',
            name='unit',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='project',
            name='po_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='payment_terms',
            field=models.CharField(choices=[('CAD', 'CAD'), ('LC', 'LC')], default='update', max_length=50),
        ),
    ]
