# Generated by Django 5.0 on 2024-03-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0003_rename_projects_updatecashin_project_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='total_actual_cash_in',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='total_actual_cash_out',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='actual_balance',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='actual_cash_in',
        ),
        migrations.RemoveField(
            model_name='summary',
            name='actual_cash_out',
        ),
    ]
