# Generated by Django 5.0 on 2024-03-11 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0006_rename_current_balance_dashboard_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='balance_data',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='cashin_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='cashout_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='chart_labels',
            field=models.JSONField(default=list),
        ),
    ]
