# Generated by Django 5.0 on 2024-03-11 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0007_dashboard_balance_data_dashboard_cashin_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='balance_data',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='cashin_data',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='cashout_data',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='chart_labels',
        ),
    ]
