# Generated by Django 5.0 on 2024-03-13 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashflow', '0008_remove_dashboard_balance_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
