# Generated by Django 5.0 on 2024-03-17 08:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('po_date', models.DateField(default=django.utils.timezone.now)),
                ('material_supplied', models.TextField()),
                ('supplier', models.CharField(max_length=255)),
                ('selling_price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.DecimalField(decimal_places=2, default=False, max_digits=10)),
                ('packing_options', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_provided', models.TextField()),
                ('packing_options', models.TextField()),
                ('purchase_price_cif_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('does_price_change_per_package', models.BooleanField(default=False)),
                ('payment_terms', models.CharField(choices=[('CAD', 'CAD'), ('LC', 'LC')], default='update', max_length=50)),
                ('lead_time_weeks', models.IntegerField()),
            ],
        ),
    ]
