# Generated by Django 5.0 on 2024-03-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_name',
            field=models.CharField(default='Supplier', max_length=255),
        ),
    ]
