# Generated by Django 5.0 on 2024-03-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supply_chain', '0003_remove_project_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='initial_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
